name: Generate report
on: workflow_dispatch
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: python:3.10-slim
    steps:	
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |			
          apt-get -y update
          apt-get install -y git openjdk-17-jre php-cli php-xml
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  
      - name: Copy env file
        run: |
          cp ./data/.env_jpeek ./.env
      - name: Info
        run: |
          python main.py info
      - name: Populate
        env:
          OTTM_SCM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ls -l ./data/*.sqlite3
          python main.py populate
          ls -l ./data/*.sqlite3
      - name: Train bugvelocity
        run: |
          python main.py train --model-name bugvelocity
      - name: Predict bugvelocity
        run: |          
          python main.py predict --model-name bugvelocity
      - name: Generate report
        run: |          
          python main.py report --output ./data
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: ./data/release.html
          retention-days: 8          
      - name: Generate export
        run: |          
          python main.py export --output ./data/export --format csv        
      - name: Upload export 
        uses: actions/upload-artifact@v3
        with:
          name: export-csv
          path: ./data/export/metrics.csv
          retention-days: 8
