name: Generate report export with image ghcr
on:
  workflow_dispatch:
    inputs:
      project-name:
        type: choice
        description: 'Project'
        options: 
        - jpeek
        - RxJava
        - guava
        - mockito
        - quarkus
      use-dataset-sqlite:
        type: boolean
        default: 'true'
        description: 'Use base sqlite in dataset repo'         
      save-update-sqlite:
        type: boolean
        default: 'false'
        description: 'Push update base sqlite after populate'        
permissions:
  contents: write
jobs:
  generate-report-export:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/stemeunier/bugprediction-fork:main
    steps:
      - name: Get env file in repo dataset
        env: 
          PROJECT: ${{ github.event.inputs.project-name }}
        run: |
          id
          cd /home/optittm-user/
          pwd
          ls -la
          wget --backups=0 https://raw.githubusercontent.com/optittm/dataset/main/${PROJECT}/.env
          sed -i 's/^OTTM_TARGET_DATABASE.*/OTTM_TARGET_DATABASE=sqlite:\/\/\/data\/${OTTM_SOURCE_PROJECT}.sqlite3/g' .env
      - name: Get sqlite in repo dataset
        env: 
          PROJECT: ${{ github.event.inputs.project-name }}
        if: ${{ github.event.inputs.use-dataset-sqlite == 'true' }}
        run: |  
          cd ./data/
          wget --backups=0 https://raw.githubusercontent.com/optittm/dataset/main/${PROJECT}/${PROJECT}.sqlite3         
      - name: Info
        run: |
          python main.py info
      - name: Populate
        env:
          OTTM_SCM_TOKEN: ${{ GITHUB.TOKEN }}
        run: |
          python main.py populate
      - name: Update base sqlite3
        env: 
          PROJECT: ${{ github.event.inputs.project-name }}
        if: ${{ github.event.inputs.save-update-sqlite == 'true' }}
        run: |          
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global --add safe.directory '*'
          git add -f ./data/${PROJECT}.sqlite3
          git commit -m "Update base sqlite3"
          git push
      - name: Train bugvelocity
        run: |
          python main.py train --model-name bugvelocity
      - name: Predict bugvelocity
        run: |          
          python main.py predict --model-name bugvelocity
      - name: Generate report
        run: |          
          python main.py report --output ./data
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: ./data/release.html
          retention-days: 8          
      - name: Generate export
        run: |          
          python main.py export --output ./data/export --format csv        
      - name: Upload export 
        uses: actions/upload-artifact@v3
        with:
          name: export-csv
          path: ./data/export/metrics.csv
          retention-days: 8
