name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: 'Projet'
        options: 
        - jpeek
        - other
      message:
        required: true
      use-emoji:
        type: boolean
        description: 'Include  emojis'
      environment:
        type: environment
        description: 'Environment to run tests against'
        options: 
        - PROD
        - DEV
jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "${{ github.event.inputs.message }} ${{ fromJSON('["", ""]')[github.event.inputs.use-emoji == 'true'] }} ${{ github.event.inputs.name }}"
