name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: 'Projet'
        options: 
        - jpeek
        - other
      message:
        required: true
      update-sqlite:
        type: boolean
        default: 'false'
        description: 'Push Update base sqlite'
      environment:
        type: environment
        description: 'Environment to run tests against'
        options: 
        - PROD
        - DEV
jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      if: ${{ github.event.inputs.update-sqlite == 'true' }}
      run: echo "${{ github.event.inputs.message }} ${{ github.event.inputs.name }}"

