name: Secret Token
on: workflow_dispatch
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: python:3.10-slim
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          apt-get -y update
          apt-get install -y git
          git --version
      - name: git config
        run: |
          git config --global user.name "stemeunier"
          git config --global user.email "stemeunier@gmail.fr"
          git config --global init.defaultBranch main
          git config --global --add safe.directory '*'
          git config --global -l
      - name: update file and push to remote
        run: |
          git init
          echo "Hello !" > hello.txt
          git add hello.txt
          git commit -m "Add file hello.txt"
          git remote add origin "https://github.com/stemeunier/bugprediction-fork.git"
          git push --set-upstream origin main
          
