name: Test push
on: workflow_dispatch
permissions:
  contents: write
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: python:3.10-slim
    steps:
      - uses: actions/checkout@v3
      - run: |
          date > generated.txt
          git config --global user.name "stemeunier"
          git config --global user.email "stemeunier@gmail.fr"
          git add .
          git commit -m "generated"
          git push
