name: Secret Token
on: workflow_dispatch
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: python:3.10-slim
    steps:	
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |			
          apt-get -y update
          apt-get install -y git
      - name: Push
        run: |
          ls -al 
          git init
          echo "Hello !" > hello.txt
          git add hello.txt
          
