name: Test push
on: workflow_dispatch
permissions:
  contents: write
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: python:3.10-slim
    steps:
      - name: Install dependencies
        run: |
          apt-get -y update
          apt-get install -y git
      - uses: actions/checkout@v3
      - name: Copy env file
        run: |
          cp ./data/.env_jpeek ./.env
      - name: Update base sqlite3
        run: |          
          date >> ./data/new.sqlite3
          echo "BASE" >> ./data/new.sqlite3
          git config --global user.name "stemeunier"
          git config --global user.email "stemeunier@gmail.fr"
          git config --global --add safe.directory '*'
          git add -f ./data/*.sqlite3
          git commit -m "Update base sqlite3"
          git push
