name: Test push
on: workflow_dispatch
permissions:
  contents: write
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: python:3.10-slim
    steps:
      - name: Install dependencies
        run: |
          apt-get -y update
          apt-get install -y git
      - uses: actions/checkout@v3
      - name: GITHUB_CONTEXT
        run: |
          echo "${GITHUB_CONTEXT}"
      - name: Actor
        run: |          
          echo ${{ github.actor }}
