name: Test push
on:
  workflow_dispatch:
    inputs:
      project-name:
        type: choice
        description: 'Project'
        options: 
        - jpeek
        - RxJava
        - guava
        - mockito
        - quarkus
      use-dataset-sqlite:
        type: boolean
        default: false
        description: 'Use base sqlite in dataset repo'         
      save-update-sqlite:
        type: boolean
        default: false
        description: 'Push update base sqlite after populate'        
permissions:
  contents: write
jobs:
  generate-report-export:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/stemeunier/bugprediction-fork:main
    env:
        IMAGE_HOME_DIR: /home/optittm-user
    defaults:
        run:
           working-directory: ${{ env.IMAGE_HOME_DIR }}
    steps:
      - name: Update base sqlite3
        env: 
          PROJECT: ${{ github.event.inputs.project-name }}
        if: ${{ github.event.inputs.save-update-sqlite == 'true' }}
        run: |
          pwd
          cd ${{ env.IMAGE_HOME_DIR }}
          ls -la 
          git init
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global --add safe.directory '*'
          git remote add origin https://github.com/stemeunier/bugprediction-fork
          git add -f ./data/${PROJECT}.sqlite3
          git commit -m "Update base sqlite3"
          git push
